# Generated by Django 4.2 on 2024-02-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmovieapp', '0002_movie_user_alter_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
