# # Generated by Django 4.2 on 2024-02-07 17:55
#
# from django.conf import settings
# from django.db import migrations, models
# import django.db.models.deletion
# import django.utils.timezone
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#         ('addmovieapp', '0003_remove_movie_user'),
#     ]
#
#     operations = [
#         migrations.AddField(
#             model_name='movie',
#             name='user',
#             field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#             preserve_default=False,
#         ),
#     ]
# Generated by Django 4.2 on 2024-02-07 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addmovieapp', '0003_remove_movie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
