# Generated by Django 4.2 on 2024-02-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmovieapp', '0004_movie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
