# Generated by Django 4.2 on 2024-02-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmovieapp', '0006_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
