# Generated by Django 4.2 on 2024-02-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmovieapp', '0003_remove_movie_user_alter_movie_id'),
        ('addmovieapp', '0007_alter_movie_id'),
    ]

    operations = [
    ]
