# Generated by Django 4.2 on 2024-02-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmovieapp', '0010_movie_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
    ]
