# Generated by Django 4.2 on 2024-02-08 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmovieapp', '0011_remove_movie_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
