# Generated by Django 4.2 on 2024-02-08 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmovieapp', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
