# Generated by Django 4.2 on 2023-10-13 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wname', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='pics')),
                ('disc', models.TextField()),
            ],
        ),
    ]
