# Generated by Django 4.2 on 2024-02-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('release_date', models.DateField()),
                ('actors', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('trailer_link', models.URLField()),
                ('poster', models.ImageField(upload_to='movie_posters')),
                ('user_rating', models.FloatField()),
                ('user_review', models.TextField()),
            ],
        ),
    ]
